#!/bin/bash
set -euo pipefail; shopt -s failglob  # 'Bash strict mode'

# Run the parser and check that it succeeds and produces the expected output.

python3 parsiflage.py "$1" >out/"$1"
diff -u ref/"$1" out/
